#dist: trusty
#sudo: required 
language: cpp
#os:
#-linux
compiler:
  - gcc
  - clang
#env:
#  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../TestCI
  - make -j
  - cd ./bin/
  - ./test_TestCI
notifications:
  email: false